version: '3.3'
services:
    # redisgraph:
    #     container_name: redisgraph-client
    #     ports:
    #         - '6377:6379'
    #     volumes:
    #         - '~/redisgraph/data:/data'
    #     restart: unless-stopped
    #     image: redislabs/redisgraph
    #     command: ["redis-server", "--loadmodule", "/usr/lib/redis/modules/redisgraph.so", "--appendonly", "yes"]
    
    graphapi:
        container_name: graphapi
        build:
            context: .
        ports:
            - '5003:8080'
        volumes:
            - './server:/usr/src/app'
